#! /bin/bash
set -e -E -v

tempdir=$(mktemp -d --tmpdir)
trap "rm -rf $tempdir" 0 1 2 15


input_xfm=$1
file=$2
grid_bias=$3
model=$4
file_mask=$5
output_xfm=$6
output_minc=$7
output_mask=$8
output_flip_minc=$9

MINC_COMPRESS_SAVE=$MINC_COMPRESS
unset MINC_COMPRESS 
#unfortunately MINC2 in compression mode is very slow for _grid processing
#todo: fix it later

xfminvert $input_xfm $tempdir/input_inv.xfm
cp $grid_bias $tempdir/bias_grid_1.mnc

cat - >>$tempdir/input_inv.xfm <<XFM
Transform_Type = Grid_Transform;
Displacement_Volume = bias_grid_1.mnc;
XFM

xfminvert $tempdir/input_inv.xfm $tempdir/input.xfm
xfm_normalize.pl $tempdir/input.xfm --like $tempdir/bias_grid_1.mnc --exact $output_xfm

if [ x$MINC_COMPRESS_SAVE != x ]; then export MINC_COMPRESS=$MINC_COMPRESS_SAVE;fi

itk_resample --like $model --transform $tempdir/input_inv.xfm --order 4 $file $output_minc
mincresample -like $model -transformation $tempdir/input_inv.xfm $file_mask $output_mask -nearest
minc_qc.pl $output_minc --mask $output_mask ${output_minc}.jpg
