#! /bin/bash
set -e -E -v

tempdir=$(mktemp -d --tmpdir)
trap "rm -rf $tempdir" 0 1 2 15


input_grid=$1
file=$2
grid_bias=$3
model=$4
file_mask=$5
output_grid=$6
output_minc=$7
output_mask=$8
output_flip_minc=$9

MINC_COMPRESS_SAVE=$MINC_COMPRESS
unset MINC_COMPRESS 

grid_proc --exp $input_grid $tempdir/

minccalc -express 'A[0]-A[1]' $input_grid $grid_bias $output_grid
minccalc -express '-A[0]' $output_grid  $tempdir/input_corr.mnc #inversion

grid_proc --exp $tempdir/input_corr.mnc $tempdir/input_inv_grid_0.mnc

cat - > $tempdir/input_inv.xfm <<XFM
MNI Transform File
Transform_Type = Linear;
Linear_Transform =
 1 0 0 0
 0 1 0 0
 0 0 1 0;
Transform_Type = Grid_Transform;
Displacement_Volume = input_inv_grid_0.mnc;
XFM

if [ x$MINC_COMPRESS_SAVE != x ]; then export MINC_COMPRESS=$MINC_COMPRESS_SAVE;fi

itk_resample --like $model --transform $tempdir/input_inv.xfm --order 4 $file $output_minc
mincresample -like $model -transformation $tempdir/input_inv.xfm $file_mask $output_mask -nearest
minc_qc.pl $output_minc --mask $output_mask ${output_minc}.jpg
