#! /bin/bash
set -e -E -v

tempdir=${TMPDIR}/$$
trap "rm -rf $tempdir" 0 1 2 15
mkdir -p $tempdir

#Usage <program> <file> <model> <file_mask> <model_mask> <output.xfm> <output_invert.xfm> 

input=$1
model=$2
input_mask=$3
model_mask=$4 
output=$5
output_inv=$6

bestlinreg_s $input $model $tempdir/left_lin.xfm -source_mask $input_mask -target_mask $model_mask -lsq12 -work_dir $tempdir 
cp $tempdir/left_lin.xfm $output

xfminvert $tempdir/left_lin.xfm $output_inv
