#! /bin/bash
set -e -E -v
tempdir=$(mktemp -d --tmpdir)
trap "rm -rf $tempdir" 0 1 2 15


#Usage <program> <file> <model> <file_mask> <model_mask> <level> <prev_xfm> <output.xfm> <output_invert.xfm>  

input=$1
model=$2
input_mask=$3
model_mask=$4 
level=$5
prev_xfm=$6
output_xfm=$7
output_inv=$8

unset MINC_COMPRESS 
#unfortunately MINC2 in compression mode is very slow for _grid processing
#todo: fix it later


if [ "$prev_xfm" != "none" ] ; then 
 xfm_normalize.pl $prev_xfm --like $model --step $level $tempdir/init.xfm
 nlfit_l $input $model $tempdir/left_nl.xfm -source_mask $input_mask -target_mask $model_mask -level $level  \
         -init_xfm $tempdir/init.xfm -work_dir $tempdir
else
 nlfit_s $input $model $tempdir/left_nl.xfm -source_mask $input_mask -target_mask $model_mask -level $level          
fi

param2xfm         $tempdir/identity.xfm
xfmconcat         $tempdir/identity.xfm $tempdir/left_nl.xfm $output_xfm
xfminvert         $output_xfm $tempdir/output_inv.xfm
xfm_normalize.pl  $tempdir/output_inv.xfm $tempdir/noutput_inv.xfm --like $model --step $level
grid_proc         --log $tempdir/noutput_inv_grid_0.mnc ${output_inv/.xfm/_grid_0.mnc}
echo ${output_inv/.xfm/_grid_0.mnc} > $output_inv