#! /bin/bash
set -e -E 
tempdir=${TMPDIR}/$$
trap "rm -rf $tempdir" 0 1 2 15
mkdir -p $tempdir

#Usage <program> <file> <model> <file_mask> <model_mask> <level> <prev_xfm> <output.xfm> <output_invert.xfm>  

input=$1
model=$2
input_mask=$3
model_mask=$4 
level=$5
prev_xfm=$6
output_xfm=$7
output_inv=$8
iterations=$9

shift 9

options="$@"

echo "$options"
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
if [ -z $iterations ]; then iterations=20;fi



unset MINC_COMPRESS 
#unfortunately MINC2 in compression mode is very slow for _grid processing
#todo: fix it later

prog=0x0x0 #dumb program

case "$level" in 
 32.0|32) prog=${iterations}x0x0x0x0x0 ;;
 16.0|16) prog=${iterations}x0x0x0x0 ;;
 8.0|8)  prog=${iterations}x0x0x0 ;;
 4.0|4)  prog=${iterations}x0x0 ;;
 2.0|2)  prog=${iterations}x0 ;;
 1.0|1)  prog=${iterations} ;;
esac 


if [ "$prev_xfm" != "none" ] ; then 
  DemonsRegistration \
  -f $input \
  -m $model \
  --num-iterations $prog \
  --fixed-mask $input_mask \
  --moving-mask $model_mask \
  --input-transform $prev_xfm \
  --outputDef-field $tempdir/left_nl.xfm \
  $options
else
  DemonsRegistration \
  -f $input \
  -m $model \
  --fixed-mask $input_mask \
  --moving-mask $model_mask \
  --num-iterations $prog \
  --outputDef-field $tempdir/left_nl.xfm \
  $options
fi

xfm_normalize.pl  $tempdir/left_nl.xfm $output_xfm --like $model --step $level
xfm_normalize.pl  $tempdir/left_nl.xfm $output_inv --like $model --step $level --invert
