#! /bin/bash
set -e -E -v
tempdir=${TMPDIR}/$$
trap "rm -rf $tempdir" 0 1 2 15
mkdir -p $tempdir

#Usage <program> <file> <file_flip> <model> <file_mask> <file_flip_mask> <model_mask> <output.xfm> <output_invert.xfm> <output_invert_flip.xfm> 

input=$1
input_flip=$2
model=$3
input_mask=$4
input_flip_mask=$5
model_mask=$6
output=$7
output_inv=$8
output_i_flip=$9

bestlinreg_s $input $model $tempdir/left_lin.xfm -source_mask $input_mask -target_mask $model_mask -lsq12 -work_dir $tempdir 
bestlinreg_s $input_flip $model $tempdir/right_lin.xfm -source_mask  $input_flip_mask -target_mask $model_mask -lsq12 -work_dir $tempdir
xfmconcat $(dirname $output)/flip.xfm $tempdir/right_lin.xfm $(dirname $output)/flip.xfm $tempdir/right_lin_flip.xfm
xfmavg $tempdir/left_lin.xfm $tempdir/right_lin_flip.xfm $output
xfminvert $output $tempdir/output_inv.xfm
cp $tempdir/output_inv.xfm $output_inv
xfmconcat $(dirname $output)/flip.xfm $tempdir/output_inv.xfm $(dirname $output)/flip.xfm $output_i_flip


