#! /bin/bash
set -e -E -v
tempdir=$(mktemp -d --tmpdir)
trap "rm -rf $tempdir" 0 1 2 15


#Usage <program> <file> <file_flip> <model> <file_mask> <file_flip_mask> <model_mask> <level> <prev_xfm> <output.xfm> <output_invert.xfm> <output_invert_flip.xfm> 

input=$1
input_flip=$2
model=$3
input_mask=$4
input_flip_mask=$5
model_mask=$6
level=$7
prev_xfm=$8
output=$9
output_inv=${10}
output_i_flip=${11}

unset MINC_COMPRESS 
#unfortunately MINC2 in compression mode is very slow for _grid processing
#todo: fix it later

flip=$(dirname $output)/flip.xfm

if [ ! -e $output ]; then

 if [ "$prev_xfm" != "none" ]; then
 # normalize previous xfm 
  xfm_normalize.pl $prev_xfm --like $model --step $level $tempdir/prev.xfm
 
  nlfit_l $input $model $tempdir/left_nl.xfm -source_mask $input_mask -target_mask $model_mask -level $level \
       -init_xfm $tempdir/prev.xfm -work_dir $tempdir 
 
  # normalize & flip previous xfm  
  xfmconcat $flip $prev_xfm $flip $tempdir/prev_flip_.xfm
  xfm_normalize.pl $tempdir/prev_flip_.xfm $tempdir/prev_flip.xfm -like $model --step $level
  
  nlfit_l $input_flip $model $tempdir/right_nl.xfm -source_mask $input_flip_mask -target_mask $model_mask \
     -level $level -init_xfm $tempdir/prev_flip.xfm  -work_dir $tempdir
 else
  nlfit_s $input $model $tempdir/left_nl.xfm -source_mask $input_mask -target_mask $model_mask -level $level
  nlfit_s $input_flip $model $tempdir/right_nl.xfm -source_mask $input_flip_mask -target_mask $model_mask \
     -level $level -work_dir $tempdir 
 fi

 xfm_normalize.pl $tempdir/left_nl.xfm $tempdir/output_left.xfm -like $model --step $level
 xfmconcat $flip $tempdir/right_nl.xfm $flip $tempdir/right_nl_flip.xfm
 #make nonlinear only
 xfm_normalize.pl $tempdir/right_nl_flip.xfm $tempdir/output_right_flip.xfm -like $model --step $level
 #average left and right flipped
 xfmavg $tempdir/output_left.xfm $tempdir/output_right_flip.xfm $output
fi

#calculate invert for averaging
xfminvert $output $tempdir/output_inv.xfm
echo $output  $output_inv $output_i_flip
xfm_normalize.pl $tempdir/output_inv.xfm $output_inv -like $model --step $level

xfmconcat $flip $tempdir/output_inv.xfm $flip $tempdir/output_flip.xfm
xfm_normalize.pl $tempdir/output_flip.xfm $output_i_flip -like $model --step $level
