#! /bin/bash
set -e -E -v

tempdir=$(mktemp -d --tmpdir)
trap "rm -rf $tempdir" 0 1 2 15


#MINC_COMPRESS_SAVE=$MINC_COMPRESS
#unset MINC_COMPRESS 
#speed up temp process 

#mincaverage -float -filelist $1 $tempdir/avg.mnc -sdfile $tempdir/sd.mnc -max_buffer_size_in_kb 131072
# but, unfortunately the nonlinear minctracc can't work with float!

cut -d ',' -f 2 $2 >$tempdir/weights
paste -d ',' $1 $tempdir/weights >$tempdir/list
volume_w_avg $tempdir/list $3

#if [ x$MINC_COMPRESS_SAVE != x ]; then export MINC_COMPRESS=$MINC_COMPRESS_SAVE;fi

#mincreshape -short $tempdir/avg.mnc $2
#mincreshape -short $tempdir/sd.mnc $3
